import type { TripDto } from "@/features/trips/types/trip.types";

export const tripDtosMock: TripDto[] = [
  {
    id: "trip-dkr-cdg-001",
    origin_city: "Dakar",
    origin_country: "SEN",
    destination_city: "Paris",
    destination_country: "FRA",
    departure_at: "2026-08-18T09:30:00.000Z",
    arrival_at: "2026-08-18T18:10:00.000Z",
    available_capacity_kg: 18,
    price_from_cents: 22000,
    currency: "EUR",
    status: "scheduled",
    transport_mode: "air",
    highlights: ["Départ confirmé", "Livraison prioritaire", "Suivi activable"],
  },
  {
    id: "trip-abj-bru-002",
    origin_city: "Abidjan",
    origin_country: "CIV",
    destination_city: "Bruxelles",
    destination_country: "BEL",
    departure_at: "2026-08-21T13:00:00.000Z",
    arrival_at: "2026-08-21T22:45:00.000Z",
    available_capacity_kg: 6,
    price_from_cents: 18000,
    currency: "EUR",
    status: "nearly_full",
    transport_mode: "air",
    highlights: ["Capacité limitée", "Voyageur vérifié", "Remise en main propre"],
  },
  {
    id: "trip-cas-bcn-003",
    origin_city: "Casablanca",
    origin_country: "MAR",
    destination_city: "Barcelone",
    destination_country: "ESP",
    departure_at: "2026-08-25T06:10:00.000Z",
    arrival_at: "2026-08-25T13:20:00.000Z",
    available_capacity_kg: 30,
    price_from_cents: 14000,
    currency: "EUR",
    status: "scheduled",
    transport_mode: "road",
    highlights: ["Grande capacité", "Flexible sur les horaires", "Transport sécurisé"],
  },
];
