/**
 * Les villes du corridor, pour la complétion.
 *
 * ═══ Pourquoi une liste embarquée ═══
 *
 * Un service tiers d'autocomplétion coûterait un appel réseau par
 * frappe, une clé à gérer, et une facture qui grandit avec le trafic
 * publicitaire — celui-là même qu'on cherche à attirer. Ici, tout tient
 * dans le bundle : la complétion est instantanée, hors ligne, gratuite.
 *
 * ═══ D'où elle vient ═══
 *
 * Extraite du référentiel d'aéroports de l'API
 * (`travel/infrastructure/data/airports.jsonl`), filtrée aux pays du
 * corridor et aux aéroports réellement desservis. Une ville à plusieurs
 * aéroports n'apparaît qu'une fois.
 *
 * ═══ Ce qu'elle n'est pas ═══
 *
 * Une liste fermée. Le champ reste libre : quelqu'un qui part d'une ville
 * absente doit pouvoir la saisir. Fermer la liste ferait renoncer
 * exactement les personnes dont le trajet nous apprendrait le plus —
 * celles qu'on n'avait pas prévues.
 *
 * 997 villes, 35 pays. Régénérée par
 * `scripts/build-cities.mjs`.
 */

/** `[ville, code pays ISO 3166-1 alpha-2]`. */
export type City = readonly [string, string];

export const CITIES: readonly City[] = [
  ["Aberdeen", "GB"],
  ["Abidjan", "CI"],
  ["Abuja", "NG"],
  ["Accra", "GH"],
  ["Agadir", "MA"],
  ["Ahl Angad", "MA"],
  ["Al Aaroui", "MA"],
  ["Albany", "US"],
  ["Albuquerque", "US"],
  ["Algiers", "DZ"],
  ["Alicante", "ES"],
  ["Amsterdam", "NL"],
  ["Anchorage", "US"],
  ["Annaba", "DZ"],
  ["Antananarivo", "MG"],
  ["Asaba", "NG"],
  ["Atlanta", "US"],
  ["Austin", "US"],
  ["Baltimore", "US"],
  ["Bamako", "ML"],
  ["Bangui", "CF"],
  ["Barcelona", "ES"],
  ["Bari", "IT"],
  ["Bastia", "FR"],
  ["Bata", "GQ"],
  ["Batna", "DZ"],
  ["Bauchi", "NG"],
  ["Beauvais", "FR"],
  ["Belfast", "GB"],
  ["Berlin", "DE"],
  ["Bilbao", "ES"],
  ["Birmingham", "US"],
  ["Birmingham, West Midlands", "GB"],
  ["Biskra", "DZ"],
  ["Bobo Dioulasso", "BF"],
  ["Boise", "US"],
  ["Bologna", "IT"],
  ["Bordeaux", "FR"],
  ["Boston", "US"],
  ["Brazzaville", "CG"],
  ["Bremen", "DE"],
  ["Brest", "FR"],
  ["Brindisi", "IT"],
  ["Bristol", "GB"],
  ["Buffalo", "US"],
  ["Burbank", "US"],
  ["Bâle / Mulhouse", "FR"],
  ["Béjaïa", "DZ"],
  ["Büren", "DE"],
  ["Cagliari", "IT"],
  ["Calden", "DE"],
  ["Calgary", "CA"],
  ["Cardiff", "GB"],
  ["Casablanca", "MA"],
  ["Caselle", "IT"],
  ["Caselle Torinese", "IT"],
  ["Catania", "IT"],
  ["Charleroi", "BE"],
  ["Charleston", "US"],
  ["Charlotte", "US"],
  ["Chicago", "US"],
  ["Chlef", "DZ"],
  ["Cincinnati / Covington", "US"],
  ["Clermont-Ferrand", "FR"],
  ["Cleveland", "US"],
  ["Colombier-Saugnieu, Rhône", "FR"],
  ["Colorado Springs", "US"],
  ["Columbus", "US"],
  ["Conakry", "GN"],
  ["Constantine", "DZ"],
  ["Corisco Island", "GQ"],
  ["Corvera", "ES"],
  ["Cotonou", "BJ"],
  ["Dakar", "SN"],
  ["Dallas", "US"],
  ["Dallas-Fort Worth", "US"],
  ["Denver", "US"],
  ["Des Moines", "US"],
  ["Detroit", "US"],
  ["Djanet", "DZ"],
  ["Dortmund", "DE"],
  ["Douala", "CM"],
  ["Dresden", "DE"],
  ["Dulles", "US"],
  ["Düsseldorf", "DE"],
  ["Edmonton", "CA"],
  ["Eindhoven", "NL"],
  ["El Matorral", "ES"],
  ["El Paso", "US"],
  ["Enegu", "NG"],
  ["Erfurt", "DE"],
  ["Es-Sénia", "DZ"],
  ["Espargos", "CV"],
  ["Faro", "PT"],
  ["Ferno", "IT"],
  ["Figari", "FR"],
  ["Firenze", "IT"],
  ["Fort Lauderdale", "US"],
  ["Fort Myers", "US"],
  ["Frankfurt am Main", "DE"],
  ["Fresno", "US"],
  ["Friedrichshafen", "DE"],
  ["Funchal", "PT"],
  ["Garoua", "CM"],
  ["Geneva", "CH"],
  ["Genova", "IT"],
  ["Girona", "ES"],
  ["Glasgow", "GB"],
  ["Goma", "CD"],
  ["Gran Canaria Island", "ES"],
  ["Grand Rapids", "US"],
  ["Greensboro", "US"],
  ["Greven", "DE"],
  ["Groningen", "NL"],
  ["Halifax", "CA"],
  ["Hamburg", "DE"],
  ["Hannover", "DE"],
  ["Hartford", "US"],
  ["Honolulu, Oahu", "US"],
  ["Houston", "US"],
  ["Ibiza", "ES"],
  ["Ilorin/Ogbomosho", "NG"],
  ["Indianapolis", "US"],
  ["Ingliston, Edinburgh", "GB"],
  ["Jacksonville", "US"],
  ["Kaduna", "NG"],
  ["Kahului", "US"],
  ["Kailua-Kona", "US"],
  ["Kano", "NG"],
  ["Kansas City", "US"],
  ["Kelowna", "CA"],
  ["Kinshasa", "CD"],
  ["Kisangani", "CD"],
  ["Knoxville/Maryville", "US"],
  ["Kumasi", "GH"],
  ["Köln", "DE"],
  ["Lagos", "NG"],
  ["Lamezia Terme", "IT"],
  ["Las Vegas", "US"],
  ["Leeds, West Yorkshire", "GB"],
  ["Lesquin", "FR"],
  ["Libreville", "GA"],
  ["Lihue, Kauai", "US"],
  ["Lisbon", "PT"],
  ["Liverpool", "GB"],
  ["Lomé", "TG"],
  ["London", "GB"],
  ["London, Essex", "GB"],
  ["Long Beach", "US"],
  ["Los Angeles", "US"],
  ["Louisville", "US"],
  ["Lubumbashi", "CD"],
  ["Luton, Luton", "GB"],
  ["Luxembourg", "LU"],
  ["Maastricht", "NL"],
  ["Madrid", "ES"],
  ["Mahajanga", "MG"],
  ["Mahón", "ES"],
  ["Maiduguri", "NG"],
  ["Malabo", "GQ"],
  ["Manchester, Greater Manchester", "GB"],
  ["Marignane, Bouches-du-Rhône", "FR"],
  ["Marrakesh", "MA"],
  ["Mellita", "TN"],
  ["Memmingen", "DE"],
  ["Memphis", "US"],
  ["Miami", "US"],
  ["Milwaukee", "US"],
  ["Minneapolis", "US"],
  ["Montpellier/Méditerranée", "FR"],
  ["Montréal", "CA"],
  ["Munich", "DE"],
  ["Myrtle Beach", "US"],
  ["Málaga", "ES"],
  ["N'Djamena", "TD"],
  ["Napoli", "IT"],
  ["Nashville", "US"],
  ["New Orleans", "US"],
  ["New York", "US"],
  ["Newark", "US"],
  ["Newcastle upon Tyne, Tyne and Wear", "GB"],
  ["Niamey", "NE"],
  ["Nice, Alpes-Maritimes", "FR"],
  ["Norfolk", "US"],
  ["Nosy Be", "MG"],
  ["Nottingham, Leicestershire", "GB"],
  ["Nouadhibou", "MR"],
  ["Nouakchott", "MR"],
  ["Nuremberg", "DE"],
  ["Oakland", "US"],
  ["Oklahoma City", "US"],
  ["Olbia", "IT"],
  ["Omaha", "US"],
  ["Ontario", "US"],
  ["Oostende", "BE"],
  ["Orio al Serio", "IT"],
  ["Orlando", "US"],
  ["Ottawa", "CA"],
  ["Ouagadougou", "BF"],
  ["Ouarzazate", "MA"],
  ["Oulad Yaich", "MA"],
  ["Palermo", "IT"],
  ["Palm Springs", "US"],
  ["Palma de Mallorca", "ES"],
  ["Paris", "FR"],
  ["Pensacola", "US"],
  ["Perugia", "IT"],
  ["Pescara", "IT"],
  ["Philadelphia", "US"],
  ["Phoenix", "US"],
  ["Pinellas Park", "US"],
  ["Pisa", "IT"],
  ["Pittsburgh", "US"],
  ["Pointe Noire", "CG"],
  ["Ponta Delgada", "PT"],
  ["Port Gentil", "GA"],
  ["Port Harcourt", "NG"],
  ["Portland", "US"],
  ["Porto", "PT"],
  ["Praia", "CV"],
  ["Prestwick, South Ayrshire", "GB"],
  ["Providence/Warwick", "US"],
  ["Quebec", "CA"],
  ["Rabat", "MA"],
  ["Rabil", "CV"],
  ["Raleigh/Durham", "US"],
  ["Ranón", "ES"],
  ["Reno", "US"],
  ["Reus", "ES"],
  ["Rheinmünster", "DE"],
  ["Richmond", "US"],
  ["Rimini", "IT"],
  ["Rochester", "US"],
  ["Rome", "IT"],
  ["Ronchi dei Legionari/Trieste", "IT"],
  ["Rotterdam", "NL"],
  ["Sacramento", "US"],
  ["Salt Lake City", "US"],
  ["San Antonio", "US"],
  ["San Bartolomé", "ES"],
  ["San Bernardino", "US"],
  ["San Diego", "US"],
  ["San Francisco", "US"],
  ["San Jose", "US"],
  ["Santa Ana", "US"],
  ["Santiago de Compostela", "ES"],
  ["Sarasota/Bradenton", "US"],
  ["Saskatoon", "CA"],
  ["Savannah", "US"],
  ["Saïss", "MA"],
  ["Schkeuditz", "DE"],
  ["Seattle", "US"],
  ["Segrate", "IT"],
  ["Seville", "ES"],
  ["Sokoto", "NG"],
  ["Spokane", "US"],
  ["St Louis", "US"],
  ["St. John's", "CA"],
  ["Strasbourg", "FR"],
  ["Stuttgart", "DE"],
  ["Syracuse", "US"],
  ["São Pedro", "CV"],
  ["Tahir", "DZ"],
  ["Tamale", "GH"],
  ["Tamanrasset", "DZ"],
  ["Tampa", "US"],
  ["Tangier", "MA"],
  ["Tenerife", "ES"],
  ["Timbuktu", "ML"],
  ["Toamasina", "MG"],
  ["Toronto", "CA"],
  ["Toulouse/Blagnac", "FR"],
  ["Treviso", "IT"],
  ["Tucson", "US"],
  ["Tulsa", "US"],
  ["Tunis", "TN"],
  ["Tétouan", "MA"],
  ["Valencia", "ES"],
  ["Vancouver", "CA"],
  ["Venezia", "IT"],
  ["Victoria", "CA"],
  ["Washington", "US"],
  ["Weeze", "DE"],
  ["West Palm Beach", "US"],
  ["Winnipeg", "CA"],
  ["Yaoundé", "CM"],
  ["Zagora", "MA"],
  ["Zaragoza", "ES"],
  ["Zaventem", "BE"],
  ["Zenata", "DZ"],
  ["Zurich", "CH"],
  ["Abbotsford", "CA"],
  ["Aberdeen", "US"],
  ["Abilene", "US"],
  ["Adak", "US"],
  ["Adrar", "DZ"],
  ["Agno", "CH"],
  ["Ajaccio", "FR"],
  ["Akron", "US"],
  ["Akure", "NG"],
  ["Al Hoceima", "MA"],
  ["Alamosa", "US"],
  ["Alava", "ES"],
  ["Aleknagik", "US"],
  ["Alexandria", "US"],
  ["Alghero", "IT"],
  ["Allentown/Bethlehem", "US"],
  ["Alliance", "US"],
  ["Almería", "ES"],
  ["Alpena", "US"],
  ["Altoona", "US"],
  ["Amarillo", "US"],
  ["Ambler", "US"],
  ["Anahim Lake", "CA"],
  ["Anaktuvuk Pass", "US"],
  ["Aniak", "US"],
  ["Annecy", "FR"],
  ["Antisiranana", "MG"],
  ["Antwerp", "BE"],
  ["Anvik", "US"],
  ["Appleton", "US"],
  ["Arcata/Eureka", "US"],
  ["Arctic Village", "US"],
  ["Asheville", "US"],
  ["Aspen", "US"],
  ["Atlantic City", "US"],
  ["Atqasuk", "US"],
  ["Augusta", "US"],
  ["Aurillac", "FR"],
  ["Avignon", "FR"],
  ["Badajoz", "ES"],
  ["Baie-Comeau", "CA"],
  ["Baker Lake", "CA"],
  ["Bakersfield", "US"],
  ["Balemartine, Argyll and Bute", "GB"],
  ["Balivanich", "GB"],
  ["Bandundu", "CD"],
  ["Bangor", "US"],
  ["Bar Harbor", "US"],
  ["Barrie", "CA"],
  ["Barter Island", "US"],
  ["Baton Rouge", "US"],
  ["Beaumont/Port Arthur", "US"],
  ["Beaver", "US"],
  ["Bedford", "US"],
  ["Bella Bella", "CA"],
  ["Bella Coola", "CA"],
  ["Belleville", "US"],
  ["Bellingham", "US"],
  ["Benin", "NG"],
  ["Bergerac", "FR"],
  ["Bern", "CH"],
  ["Besalampy", "MG"],
  ["Bethel", "US"],
  ["Biarritz", "FR"],
  ["Billings", "US"],
  ["Binghamton", "US"],
  ["Bishop", "US"],
  ["Bismarck", "US"],
  ["Blanc-Sablon", "CA"],
  ["Bloomington/Normal", "US"],
  ["Blountville", "US"],
  ["Bolzano", "IT"],
  ["Bonaventure", "CA"],
  ["Bonnyville", "CA"],
  ["Bordj Badji Mokhtar", "DZ"],
  ["Bouaké", "CI"],
  ["Bouarfa", "MA"],
  ["Boulder City", "US"],
  ["Bournemouth", "GB"],
  ["Bozeman", "US"],
  ["Bradford", "US"],
  ["Bragança", "PT"],
  ["Brainerd", "US"],
  ["Brandon", "CA"],
  ["Branson", "US"],
  ["Breslau", "CA"],
  ["Bridgeport", "US"],
  ["Brive", "FR"],
  ["Brownsville", "US"],
  ["Brunswick", "US"],
  ["Bunia", "CD"],
  ["Burlington", "US"],
  ["Burns Lake", "CA"],
  ["Butte", "US"],
  ["Béchar", "DZ"],
  ["Béziers", "FR"],
  ["Caen", "FR"],
  ["Calabar", "NG"],
  ["Calvi", "FR"],
  ["Cambridge Bay", "CA"],
  ["Campbell River", "CA"],
  ["Campbeltown", "GB"],
  ["Campo nell'Elba", "IT"],
  ["Cap Skirring", "SN"],
  ["Cape Girardeau", "US"],
  ["Cape Lisburne", "US"],
  ["Carcassonne", "FR"],
  ["Carlsbad", "US"],
  ["Cascais", "PT"],
  ["Casper", "US"],
  ["Castellón de la Plana", "ES"],
  ["Castlegar", "CA"],
  ["Castres", "FR"],
  ["Cedar City", "US"],
  ["Cedar Rapids", "US"],
  ["Chadron", "US"],
  ["Chalons en Champagne", "FR"],
  ["Chambéry", "FR"],
  ["Charlo", "CA"],
  ["Charlottesville", "US"],
  ["Charlottetown", "CA"],
  ["Chattanooga", "US"],
  ["Cheyenne", "US"],
  ["Chibougamau", "CA"],
  ["Chicago/Rockford", "US"],
  ["Churchill", "CA"],
  ["Cincinnati", "US"],
  ["Clovis", "US"],
  ["Cody", "US"],
  ["Cold Bay", "US"],
  ["College Station", "US"],
  ["Columbia", "US"],
  ["Columbus/W Point/Starkville", "US"],
  ["Comiso", "IT"],
  ["Comox", "CA"],
  ["Concord", "US"],
  ["Coral Harbour", "CA"],
  ["Cordova", "US"],
  ["Corpus Christi", "US"],
  ["Cortez", "US"],
  ["Cranbrook", "CA"],
  ["Crescent City", "US"],
  ["Culleredo", "ES"],
  ["Córdoba", "ES"],
  ["Darlington, Durham", "GB"],
  ["Dauphin", "CA"],
  ["Dawson City", "CA"],
  ["Dayton", "US"],
  ["Daytona Beach", "US"],
  ["Deadhorse", "US"],
  ["Deauville", "FR"],
  ["Decatur", "US"],
  ["Deer Lake", "CA"],
  ["Deering", "US"],
  ["Derry, Derry and Strabane", "GB"],
  ["Destin", "US"],
  ["Devils Lake", "US"],
  ["Dickinson", "US"],
  ["Dijon", "FR"],
  ["Dillingham", "US"],
  ["Dinard", "FR"],
  ["Dodge City", "US"],
  ["Dole", "FR"],
  ["Dothan", "US"],
  ["Dover", "US"],
  ["Dubois", "US"],
  ["Dubuque", "US"],
  ["Duluth", "US"],
  ["Dundee", "GB"],
  ["Durango", "US"],
  ["Eagle", "US"],
  ["Eastsound", "US"],
  ["Eau Claire", "US"],
  ["Eday", "GB"],
  ["Egegik", "US"],
  ["El Atteuf", "DZ"],
  ["El Dorado", "US"],
  ["El Hierro Island", "ES"],
  ["El Menia", "DZ"],
  ["Elko", "US"],
  ["Elmira/Corning", "US"],
  ["Emmonak", "US"],
  ["Enfidha", "TN"],
  ["Eoligarry", "GB"],
  ["Erie", "US"],
  ["Errachidia", "MA"],
  ["Escanaba", "US"],
  ["Essaouira", "MA"],
  ["Eugene", "US"],
  ["Evansville", "US"],
  ["Everett", "US"],
  ["Ewing Township", "US"],
  ["Exeter, Devon", "GB"],
  ["Fairbanks", "US"],
  ["Falconara Marittima", "IT"],
  ["Fargo", "US"],
  ["Fayetteville", "US"],
  ["Fayetteville/Springdale/Rogers", "US"],
  ["Flagstaff", "US"],
  ["Flint", "US"],
  ["Florence", "US"],
  ["Foggia", "IT"],
  ["Forlì", "IT"],
  ["Fort Cavazos", "US"],
  ["Fort Chipewyan", "CA"],
  ["Fort Dodge", "US"],
  ["Fort Frances", "CA"],
  ["Fort Leonard Wood", "US"],
  ["Fort McMurray", "CA"],
  ["Fort Nelson", "CA"],
  ["Fort Saint John", "CA"],
  ["Fort Simpson", "CA"],
  ["Fort Smith", "US"],
  ["Fort Smith", "CA"],
  ["Fort Wayne", "US"],
  ["Fort Worth", "US"],
  ["Fort Yukon", "US"],
  ["Franceville", "GA"],
  ["Fredericton", "CA"],
  ["Freeland", "US"],
  ["Friday Harbor", "US"],
  ["Gainesville", "US"],
  ["Galena", "US"],
  ["Gallup", "US"],
  ["Gambell", "US"],
  ["Gander", "CA"],
  ["Gao", "ML"],
  ["Garden City", "US"],
  ["Gary", "US"],
  ["Gaspé", "CA"],
  ["Gatineau", "CA"],
  ["Gbadolite", "CD"],
  ["Gemena", "CD"],
  ["Gillette", "US"],
  ["Glasgow", "US"],
  ["Glendive", "US"],
  ["Goin", "FR"],
  ["Gombe", "NG"],
  ["Goose Bay", "CA"],
  ["Granada", "ES"],
  ["Grand Canyon - Tusayan", "US"],
  ["Grand Forks", "US"],
  ["Grand Island", "US"],
  ["Grand Junction", "US"],
  ["Grande Prairie", "CA"],
  ["Gravenhurst", "CA"],
  ["Great Falls", "US"],
  ["Green Bay", "US"],
  ["Greenville", "US"],
  ["Greenville/Greer/Spartanburg", "US"],
  ["Grenoble", "FR"],
  ["Grimsby, Lincolnshire", "GB"],
  ["Grâce-Hollogne", "BE"],
  ["Guemar", "DZ"],
  ["Gulfport", "US"],
  ["Gulkana", "US"],
  ["Gunnison", "US"],
  ["Gustavus", "US"],
  ["Gwinn", "US"],
  ["Hagerstown", "US"],
  ["Hailey", "US"],
  ["Haines", "US"],
  ["Hamilton", "CA"],
  ["Hana", "US"],
  ["Hancock", "US"],
  ["Harlingen", "US"],
  ["Harrisburg", "US"],
  ["Harrison", "US"],
  ["Hassi Messaoud", "DZ"],
  ["Havre", "US"],
  ["Havre-Saint-Pierre", "CA"],
  ["Hawthorne", "US"],
  ["Hay River", "CA"],
  ["Hayden", "US"],
  ["Hays", "US"],
  ["Helena", "US"],
  ["Hibbing", "US"],
  ["High Level", "CA"],
  ["Hilo", "US"],
  ["Hilton Head Island", "US"],
  ["Hobbs", "US"],
  ["Holy Cross", "US"],
  ["Homer", "US"],
  ["Hondarribia", "ES"],
  ["Horta", "PT"],
  ["Hot Springs", "US"],
  ["Huntington", "US"],
  ["Huntsville", "US"],
  ["Huslia", "US"],
  ["Hyannis", "US"],
  ["Hyères, Var", "FR"],
  ["Ibadan", "NG"],
  ["Idaho Falls", "US"],
  ["Iliamna", "US"],
  ["Illizi", "DZ"],
  ["Imperial", "US"],
  ["In Aménas", "DZ"],
  ["In Salah", "DZ"],
  ["International Falls", "US"],
  ["Inuvik", "CA"],
  ["Inverness", "GB"],
  ["Iqaluit", "CA"],
  ["Isiro", "CD"],
  ["Island Lake", "CA"],
  ["Isle of Islay, Argyll and Bute", "GB"],
  ["Islip", "US"],
  ["Isola di Capo Rizzuto", "IT"],
  ["Ithaca", "US"],
  ["Jackson", "US"],
  ["Jamestown", "US"],
  ["Jerez de la Frontera", "ES"],
  ["Johnstown", "US"],
  ["Jonesboro", "US"],
  ["Joplin", "US"],
  ["Jos", "NG"],
  ["Juneau", "US"],
  ["Kalamazoo", "US"],
  ["Kalemie", "CD"],
  ["Kalispell", "US"],
  ["Kamloops", "CA"],
  ["Kananga", "CD"],
  ["Kasabonika", "CA"],
  ["Katsina", "NG"],
  ["Kaunakakai", "US"],
  ["Kayes", "ML"],
  ["Kearney", "US"],
  ["Kenai", "US"],
  ["Kenora", "CA"],
  ["Ketchikan", "US"],
  ["Key West", "US"],
  ["Kiana", "US"],
  ["Kikwit", "CD"],
  ["Kincheloe", "US"],
  ["Kindu", "CD"],
  ["King Salmon", "US"],
  ["Kingsford", "US"],
  ["Kirksville", "US"],
  ["Kirkwall, Orkney Islands", "GB"],
  ["Klawock", "US"],
  ["Kodiak", "US"],
  ["Kolwezi", "CD"],
  ["Korhogo", "CI"],
  ["Kotzebue", "US"],
  ["Kuujjuaq", "CA"],
  ["Kuujjuarapik", "CA"],
  ["La Crosse", "US"],
  ["La Grande Rivière", "CA"],
  ["La Rochelle", "FR"],
  ["La Ronge", "CA"],
  ["La Seu d'Urgell Pyrenees and Andorra", "ES"],
  ["La Virgen del Camino", "ES"],
  ["Laage", "DE"],
  ["Lafayette", "US"],
  ["Laghouat", "DZ"],
  ["Lahaina", "US"],
  ["Lake Charles", "US"],
  ["Lake Havasu City", "US"],
  ["Lakeland", "US"],
  ["Lampedusa", "IT"],
  ["Lanai City", "US"],
  ["Lancaster", "US"],
  ["Lansing", "US"],
  ["Laramie", "US"],
  ["Laredo", "US"],
  ["Las Cruces", "US"],
  ["Latrobe", "US"],
  ["Lawton", "US"],
  ["Le Mans, Sarthe", "FR"],
  ["Lebanon", "US"],
  ["Lerwick, Shetland", "GB"],
  ["Les Îles-de-la-Madeleine", "CA"],
  ["Lethbridge", "CA"],
  ["Levaldigi", "IT"],
  ["Lewisburg", "US"],
  ["Lewiston", "US"],
  ["Lexington", "US"],
  ["Liberal", "US"],
  ["Limoges/Bellegarde", "FR"],
  ["Lincoln", "US"],
  ["Little Rock", "US"],
  ["Lleida", "ES"],
  ["Lloydminster", "CA"],
  ["London", "CA"],
  ["Longview", "US"],
  ["Lorient/Lann/Bihoué", "FR"],
  ["Lubbock", "US"],
  ["Lynchburg", "US"],
  ["Lynn Lake", "CA"],
  ["Lübeck", "DE"],
  ["Macon", "US"],
  ["Madison", "US"],
  ["Makokou", "GA"],
  ["Makurdi", "NG"],
  ["Mammoth Lakes", "US"],
  ["Mananjary", "MG"],
  ["Manchester", "US"],
  ["Manhattan", "US"],
  ["Mannheim", "DE"],
  ["Marion", "US"],
  ["Maroantsetra", "MG"],
  ["Maroua", "CM"],
  ["Mason City", "US"],
  ["Massena", "US"],
  ["Masset", "CA"],
  ["Mbandaka", "CD"],
  ["Mbuji Mayi", "CD"],
  ["McAllen", "US"],
  ["McCall", "US"],
  ["McCook", "US"],
  ["McGrath", "US"],
  ["Mecheria", "DZ"],
  ["Medford", "US"],
  ["Medicine Hat", "CA"],
  ["Mekoryuk", "US"],
  ["Melbourne", "US"],
  ["Melilla", "ES"],
  ["Mengomeyén", "GQ"],
  ["Merced", "US"],
  ["Meridian", "US"],
  ["Mesa", "US"],
  ["Michigan City", "US"],
  ["Midland", "US"],
  ["Mineral Wells", "US"],
  ["Minot", "US"],
  ["Missoula", "US"],
  ["Moab", "US"],
  ["Mobile", "US"],
  ["Moline", "US"],
  ["Monastir", "TN"],
  ["Moncton", "CA"],
  ["Monroe", "US"],
  ["Mont-Joli", "CA"],
  ["Monterey", "US"],
  ["Montgomery", "US"],
  ["Montichiari", "IT"],
  ["Montrose", "US"],
  ["Moosonee", "CA"],
  ["Morgantown", "US"],
  ["Morondava", "MG"],
  ["Moselle", "US"],
  ["Mosinee", "US"],
  ["Muscle Shoals", "US"],
  ["Muskegon", "US"],
  ["N'Gaoundéré", "CM"],
  ["Nakina", "CA"],
  ["Nanaimo", "CA"],
  ["Nantes", "FR"],
  ["Nantucket", "US"],
  ["Natashquan", "CA"],
  ["New Bedford", "US"],
  ["New Bern", "US"],
  ["New Haven", "US"],
  ["Newburgh", "US"],
  ["Newport", "US"],
  ["Newport News", "US"],
  ["Newquay", "GB"],
  ["Niagara Falls", "US"],
  ["Niagara-on-the-Lake", "CA"],
  ["Nome", "US"],
  ["Norman Wells", "CA"],
  ["North Bay", "CA"],
  ["North Bend", "US"],
  ["North Platte", "US"],
  ["Northway", "US"],
  ["Norwich, Norfolk", "GB"],
  ["Nuiqsut", "US"],
  ["Nîmes/Garons", "FR"],
  ["Ocean City", "US"],
  ["Ogden", "US"],
  ["Ogdensburg", "US"],
  ["Okpe", "NG"],
  ["Olympia", "US"],
  ["Ouargla", "DZ"],
  ["Owensboro", "US"],
  ["Owerri", "NG"],
  ["Oyem", "GA"],
  ["Paducah", "US"],
  ["Page", "US"],
  ["Pamplona", "ES"],
  ["Panama City Beach", "US"],
  ["Pantelleria", "IT"],
  ["Parkersburg", "US"],
  ["Parma", "IT"],
  ["Pasco", "US"],
  ["Pau/Pyrénées", "FR"],
  ["Peace River", "CA"],
  ["Pellston", "US"],
  ["Pendleton", "US"],
  ["Penticton", "CA"],
  ["Peoria", "US"],
  ["Perpignan/Rivesaltes", "FR"],
  ["Peterborough", "CA"],
  ["Petersburg", "US"],
  ["Pickle Lake", "CA"],
  ["Pico Island", "PT"],
  ["Pierre", "US"],
  ["Platinum", "US"],
  ["Plattsburgh", "US"],
  ["Pocatello", "US"],
  ["Point Lay", "US"],
  ["Points North Landing", "CA"],
  ["Poitiers/Biard", "FR"],
  ["Port Hardy", "CA"],
  ["Port Heiden", "US"],
  ["Port-Menier", "CA"],
  ["Portimão", "PT"],
  ["Portsmouth", "US"],
  ["Powell River", "CA"],
  ["Praia da Vitória", "PT"],
  ["Preguiça", "CV"],
  ["Prescott", "US"],
  ["Presque Isle", "US"],
  ["Prince Albert", "CA"],
  ["Prince George", "CA"],
  ["Prince Rupert", "CA"],
  ["Provo", "US"],
  ["Pueblo", "US"],
  ["Pullman", "US"],
  ["Punta Gorda", "US"],
  ["Puvirnituq", "CA"],
  ["Qualicum Beach", "CA"],
  ["Quesnel", "CA"],
  ["Quincy", "US"],
  ["Rankin Inlet", "CA"],
  ["Rapid City", "US"],
  ["Red Lake", "CA"],
  ["Redding", "US"],
  ["Redmond", "US"],
  ["Reggio Calabria", "IT"],
  ["Regina", "CA"],
  ["Resolute Bay", "CA"],
  ["Rhinelander", "US"],
  ["Richlands", "US"],
  ["Rimouski", "CA"],
  ["Riverton", "US"],
  ["Roanoke", "US"],
  ["Roberval", "CA"],
  ["Rock Springs", "US"],
  ["Rockland", "US"],
  ["Rodez/Marcillac", "FR"],
  ["Roswell", "US"],
  ["Rouyn-Noranda", "CA"],
  ["Ruby", "US"],
  ["Rutland", "US"],
  ["Saarbrücken", "DE"],
  ["Saguenay", "CA"],
  ["Saint Cloud", "US"],
  ["Saint John", "CA"],
  ["Saint-Jacques-de-la-Lande, Ille-et-Vilaine", "FR"],
  ["Saint-Léonard", "CA"],
  ["Saint-Nazaire/Montoir", "FR"],
  ["Salamanca", "ES"],
  ["Salem", "US"],
  ["Salerno", "IT"],
  ["Salina", "US"],
  ["Salisbury", "US"],
  ["Salmon", "US"],
  ["Sambava", "MG"],
  ["San Angelo", "US"],
  ["San Carlos", "US"],
  ["San Luis Obispo", "US"],
  ["Sand Point", "US"],
  ["Sandspit", "CA"],
  ["Sandy Lake", "CA"],
  ["Sanirajak", "CA"],
  ["Santa Barbara", "US"],
  ["Santa Cruz da Graciosa", "PT"],
  ["Santa Cruz das Flores", "PT"],
  ["Santa Fe", "US"],
  ["Santa Maria", "US"],
  ["Santa Rosa", "US"],
  ["Santander", "ES"],
  ["Saranac Lake", "US"],
  ["Sault Ste Marie", "CA"],
  ["Savoonga", "US"],
  ["Savoy", "US"],
  ["Schefferville", "CA"],
  ["Scottsbluff", "US"],
  ["Sekondi-Takoradi", "GH"],
  ["Sept-Îles", "CA"],
  ["Sfax", "TN"],
  ["Sheridan", "US"],
  ["Show Low", "US"],
  ["Shreveport", "US"],
  ["Sidney", "US"],
  ["Silver City", "US"],
  ["Sioux City", "US"],
  ["Sioux Falls", "US"],
  ["Sioux Lookout", "CA"],
  ["Sitka", "US"],
  ["Smithers", "CA"],
  ["South Bend", "US"],
  ["South Tetagouche", "CA"],
  ["Southampton", "GB"],
  ["Southend-on-Sea, Essex", "GB"],
  ["Springfield", "US"],
  ["St Augustine", "US"],
  ["St George", "US"],
  ["St Paul Island", "US"],
  ["St-Augustin", "CA"],
  ["St. Anthony", "CA"],
  ["St. Gallen", "CH"],
  ["Sta Cruz de la Palma, La Palma Island", "ES"],
  ["State College", "US"],
  ["Stephenville", "CA"],
  ["Stillwater", "US"],
  ["Stockton", "US"],
  ["Stony Rapids", "CA"],
  ["Stornoway, Western Isles", "GB"],
  ["Sudbury", "CA"],
  ["Sunyani", "GH"],
  ["Sydney", "CA"],
  ["Sylt", "DE"],
  ["Sétif", "DZ"],
  ["Sévaré", "ML"],
  ["Tabarka", "TN"],
  ["Tacoma", "US"],
  ["Tallahassee", "US"],
  ["Tan Tan", "MA"],
  ["Taos", "US"],
  ["Tarbes/Lourdes/Pyrénées", "FR"],
  ["Telluride", "US"],
  ["Terrace", "CA"],
  ["Teterboro", "US"],
  ["Texarkana", "US"],
  ["The Pas", "CA"],
  ["Thief River Falls", "US"],
  ["Thompson", "CA"],
  ["Thunder Bay", "CA"],
  ["Timimoun", "DZ"],
  ["Timmins", "CA"],
  ["Tindouf", "DZ"],
  ["Tofino", "CA"],
  ["Toledo", "US"],
  ["Toliara", "MG"],
  ["Touggourt", "DZ"],
  ["Tours, Indre-et-Loire", "FR"],
  ["Tozeur", "TN"],
  ["Trapani", "IT"],
  ["Traverse City", "US"],
  ["Truckee", "US"],
  ["Tupelo", "US"],
  ["Twin Falls", "US"],
  ["Tyler", "US"],
  ["Tébessi", "DZ"],
  ["Tôlanaro", "MG"],
  ["Unalakleet", "US"],
  ["Unalaska", "US"],
  ["Utopia Creek", "US"],
  ["Utqiaġvik", "US"],
  ["Uyo", "NG"],
  ["Val-d'Or", "CA"],
  ["Valdez", "US"],
  ["Valdosta", "US"],
  ["Valladolid", "ES"],
  ["Valparaiso", "US"],
  ["Velas", "PT"],
  ["Vernal", "US"],
  ["Vero Beach", "US"],
  ["Victoria", "US"],
  ["Vigo", "ES"],
  ["Vila Baleira", "PT"],
  ["Vila Real", "PT"],
  ["Vila do Maio", "CV"],
  ["Vila do Porto", "PT"],
  ["Viseu", "PT"],
  ["Vohilava", "MG"],
  ["Wabush", "CA"],
  ["Waco", "US"],
  ["Waimea", "US"],
  ["Wainwright", "US"],
  ["Walla Walla", "US"],
  ["Waterloo", "US"],
  ["Watertown", "US"],
  ["Watson Lake", "CA"],
  ["Wenatchee", "US"],
  ["West Lafayette", "US"],
  ["West Yellowstone", "US"],
  ["Westerly", "US"],
  ["Weyers Cave", "US"],
  ["White Plains", "US"],
  ["Whitecourt", "CA"],
  ["Whitehorse", "CA"],
  ["Wiarton", "CA"],
  ["Wichita", "US"],
  ["Wichita Falls", "US"],
  ["Wick", "GB"],
  ["Wilkes-Barre/Scranton", "US"],
  ["Williams Lake", "CA"],
  ["Williamsport", "US"],
  ["Williston", "US"],
  ["Wilmington", "US"],
  ["Windsor", "CA"],
  ["Wolf Point", "US"],
  ["Worcester", "US"],
  ["Wrangell", "US"],
  ["Wurster Nordseeküste", "DE"],
  ["Yakima", "US"],
  ["Yakutat", "US"],
  ["Yellowknife", "CA"],
  ["Yola", "NG"],
  ["Yuma", "US"],
  ["Ziguinchor", "SN"],
  ["Zinder", "NE"],
  ["Zirchow", "DE"],
  ["Zouérate", "MR"],
];

/** Les pays servis, pour afficher « Douala, Cameroun » plutôt qu'un code. */
export const COUNTRY_NAMES: Record<string, string> = {
  "FR": "France",
  "BE": "Belgique",
  "CH": "Suisse",
  "DE": "Allemagne",
  "ES": "Espagne",
  "IT": "Italie",
  "GB": "Royaume-Uni",
  "NL": "Pays-Bas",
  "PT": "Portugal",
  "LU": "Luxembourg",
  "CA": "Canada",
  "US": "États-Unis",
  "CM": "Cameroun",
  "SN": "Sénégal",
  "CI": "Côte d'Ivoire",
  "ML": "Mali",
  "GA": "Gabon",
  "CG": "Congo",
  "CD": "RD Congo",
  "TG": "Togo",
  "BJ": "Bénin",
  "BF": "Burkina Faso",
  "GN": "Guinée",
  "NE": "Niger",
  "TD": "Tchad",
  "MA": "Maroc",
  "DZ": "Algérie",
  "TN": "Tunisie",
  "MR": "Mauritanie",
  "CF": "Centrafrique",
  "GQ": "Guinée équatoriale",
  "MG": "Madagascar",
  "CV": "Cap-Vert",
  "GH": "Ghana",
  "NG": "Nigeria"
};
